### PR TITLE
Merge everything from `beta` into `main`, updated readme and man page

### PR DESCRIPTION
**Pull request by WTechNinja**
If anything needs fixing, let me know. Also if you have a better idea for how to have both a beta and main version, tell me

### CODE REVIEW

**Comment by kaonkaon** [comment]
Sorry for late reply :" i was overwhelmed by college thing
thank you for merge `beta` into `main` for me! i will merge this 

>Also if you have a better idea for how to have both a beta and main version, tell me

im thinking of completely remove README.md from beta branch, and put all `beta` branch description in to `main` branch README.md. what do you think?

but i think its easier to just make branch for change and delete those branch afterward, just like what you said. 

and again im really sorry for late reply

**Comment by WTechNinja** [comment]
No worries, and wow. Can't believe I didn't think of that. That should work beautifully

**Comment by kaonkaon** [comment]
but man, im kinda gives up to maintain those beta branch. the change we made is not that "bloody edge", and we will merge it to `main` anyway as soon as the thing is ready. it almost no reason to maintain beta branch

so yeah, lets use branch for change, and delete after merging

oh and thank you for helping me merge everything!

**Comment by WTechNinja** [comment]
Fair. When I update the readme I'll add something saying "we might be testing new features in the branches, feel free to look around" 
I'll probably mess with it tomorrow

And you're very welcome

**Pull request merged**
