### PR TITLE
Fixed typos, and added more details to README.md

### PR DESCRIPTION
**Pull request by WTechNinja**
I reworded some stuff, redid the configuration section, fixed a couple of typos, and then added some details to the man page section.

Also, just a note, after I made the manpage earlier I remembered I'm running wayland (not x11) and the script doesn't work for me (lol, whoops) so I have a branch that works on wayland called `eses-w`. I haven't changed much, but feel free to steal code back if you ever want to.

### CODE REVIEW

**Comment by kaonkaon** [comment]
woah cool! sorry for bad english, English is not my native language so yeah

i saw your branch for wayland, thats v cool. i remember there was a dude saying that he "downvote" me because of "only xorg" support
i want to support wayland to, im thinking for something like "auto display server detection", so it will detect what display server are user using, and use the script that work for their display server. is this possible?

oh yeah and i will merge this, thank you again for the help! im looking forward to working with you

**Comment by WTechNinja** [comment]
I'm looking forward to working together with you as well! I've never had a script check which display server you're using, but I'm sure someone's done it, and if that's too hard we can have an option for it in the config

**Comment by WTechNinja** [comment]
I'm going to bed, but there's an environment variable `XDG_SESSION_TYPE` that should work for this. I could be wrong, but I think it *should* always be set, and it'll either be `wayland` or `x11`.  
I was just testing it out with this and it seems to work (could be wrong)

```
#!/bin/bash

if [ $XDG_SESSION_TYPE == 'wayland' ]; 
then echo "wayland"
else echo "x11"
fi
```
I'll mess with it more later

**Comment by kaonkaon** [comment]
OH GOD THATS WHAT I NEED

i made something that maybe working, i simply added what u suggested and everything on your eses-w, its on branch named "beta" for now

i hope u, as wayland user, will test this

but hey, i think this belongs to your repo

**Comment by kaonkaon** [comment]
oh and have a goodnight m8

**Pull request merged**
